data_types_dir = data_types/
game_mechanics_dir = game_mechanics/

all_debug:
	$(MAKE) -C $(data_types_dir) all_debug
	$(MAKE) -C $(game_mechanics_dir) all_debug


all:
	$(MAKE) -C $(data_types_dir) all
	$(MAKE) -C $(game_mechanics_dir) all
